<a href="https://colab.research.google.com/github/bhatmohit/Financial_Statement_Analysis/blob/main/Accruals_and_Cash_Flows.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Load Data

In [1]:
import pandas as pd
import numpy as np

from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [17]:
df = pd.read_pickle(r'drive/MyDrive/Financial_Statement_Analysis/Data/FSAData.pkl')

# EDA - Data Understanding

In [18]:
df.head()

,gvkey,datadate,cik,conm,sich,fyear,revt,cogs,xsga,xrd,...,mib,ceq,seq,pstk,prcc_f,csho,permno,annret,restated,icw
0,001004,1990-05-31,0000001750,AAR CORP,5080.0,1989.0,444.875,336.931,53.912,NaN,...,0.0,189.548,189.548,0.0,21.249998,16.082,54594,0.062929,NaN,NaN
1,001004,1991-05-31,0000001750,AAR CORP,5080.0,1990.0,466.542,366.040,58.545,NaN,...,0.0,193.778,193.778,0.0,14.124999,15.891,54594,-0.235340,NaN,NaN
2,001004,1992-05-31,0000001750,AAR CORP,5080.0,1991.0,422.657,331.056,56.910,NaN,...,0.0,196.737,196.737,0.0,12.874998,15.899,54594,0.147498,NaN,NaN
3,001004,1993-05-31,0000001750,AAR CORP,5080.0,1992.0,382.780,307.436,52.093,NaN,...,0.0,189.216,189.216,0.0,13.499999,15.901,54594,0.052125,NaN,NaN
4,001004,1994-05-31,0000001750,AAR CORP,5080.0,1993.0,407.754,328.562,50.086,NaN,...,0.0,189.488,189.488,0.0,14.374998,15.906,54594,0.274547,NaN,NaN

In [19]:
df.columns.values

array(['gvkey', 'datadate', 'cik', 'conm', 'sich', 'fyear', 'revt',
       'cogs', 'xsga', 'xrd', 'dp', 'dpc', 'nopi', 'xint', 'txt', 'spi',
       'ib', 'xidoc', 'ni', 'ci', 'oancf', 'ivncf', 'fincf', 'capx',
       'recch', 'invch', 'apalch', 'aqc', 'dltis', 'dltr', 'dv', 'act',
       'invt', 'rect', 'che', 'ppent', 'intan', 'at', 'lct', 'ap', 'lt',
       'mib', 'ceq', 'seq', 'pstk', 'prcc_f', 'csho', 'permno', 'annret',
       'restated', 'icw'], dtype=object)

In [20]:
df.describe()

,sich,fyear,revt,cogs,xsga,xrd,dp,dpc,nopi,xint,...,mib,ceq,seq,pstk,prcc_f,csho,permno,annret,restated,icw
count,73417.000000,73696.000000,73696.000000,73696.000000,58405.000000,38767.000000,69834.000000,71697.000000,73689.000000,67289.000000,...,67304.000000,73624.000000,73696.000000,73601.000000,73696.000000,73696.000000,73696.000000,73396.000000,50668.000000,41145.000000
mean,4728.003623,2005.000380,5737.311037,3838.753901,1032.949628,236.812882,336.464990,346.428697,14.441432,184.828676,...,71.250034,3271.938952,3334.768496,59.404982,55.497155,211.370430,61511.940865,0.151033,0.105925,0.036189
std,1931.752434,8.874866,19925.104992,15107.476281,3463.338284,988.820988,1328.571874,1364.818687,827.933703,1242.827568,...,696.411811,12289.986509,12577.957443,849.744455,1185.915382,666.564193,28044.079136,0.644044,0.307744,0.186763
min,100.000000,1989.000000,-15009.328000,-12424.689000,-283.000000,0.000000,-7.909000,-87.000000,-31459.012000,-367.330000,...,-3121.206000,-96620.000000,-86154.000000,-252.000000,0.031000,0.001000,10002.000000,-1.316185,0.000000,0.000000
25%,3317.000000,1997.000000,342.086750,160.544750,72.731000,1.317500,13.567000,15.911000,0.000000,4.190000,...,0.000000,221.934750,226.868250,0.000000,15.670000,28.249750,36346.000000,-0.147321,0.000000,0.000000
50%,4813.000000,2005.000000,1029.009500,592.562000,198.365000,23.400000,47.864500,53.998000,2.851000,25.796000,...,0.000000,618.160500,631.440000,0.000000,27.060000,57.739500,76110.000000,0.085149,0.000000,0.000000
75%,6324.000000,2013.000000,3423.886500,2159.533000,612.000000,93.447500,175.720500,186.709000,16.818000,100.000000,...,0.000000,1848.019250,1880.925000,0.000000,44.410000,143.659000,84386.000000,0.333333,0.000000,0.000000
max,9997.000000,2021.000000,556933.000000,435726.253000,129933.000000,42740.000000,52892.000000,52444.000000,23178.000000,92108.615000,...,44312.804000,443164.000000,443164.000000,81248.000000,141600.000000,29058.361000,93436.000000,35.385544,1.000000,1.000000

# Data Preparation

## Calculate Accruals and Cash Flows (scaled by total assets)

Accruals = Net Income(ni) - Cash Flows from Net Operating Activities(oancf)

In [21]:
df['accruals'] = (df['ni'] - df['oancf'])/df['at']
df['scaled_oancf'] = df['oancf']/df['at']
df[['accruals', 'scaled_oancf']]

       accruals  scaled_oancf
0      0.016174      0.049858
1     -0.058138      0.097092
2      0.003050      0.022294
3     -0.045250      0.046025
4      0.006697      0.016036
...         ...           ...
73691 -0.024481      0.072474
73692 -0.089599      0.078789
73693 -0.106623      0.155831
73694 -0.057921      0.098198
73695 -0.083368     -0.007670

[73696 rows x 2 columns]

## Data Cleaning

Remove inf values

In [22]:
df[['accruals', 'scaled_oancf']].describe()

           accruals  scaled_oancf
count  7.369600e+04  7.369600e+04
mean           -inf           inf
std             NaN           NaN
min            -inf -9.047293e+00
25%   -8.089700e-02  3.803913e-02
50%   -4.297630e-02  8.159816e-02
75%   -1.232189e-02  1.316725e-01
max    1.689776e+02           inf

In [23]:
df[['accruals', 'scaled_oancf']] = df[['accruals', 'scaled_oancf']].replace([-np.inf, np.inf], np.nan)
# df[['scaled_oancf']].replace([-np.inf, np.inf], np.nan)
df.dropna(subset=['accruals', 'scaled_oancf'])
df[['accruals', 'scaled_oancf']].describe().round(2)

       accruals  scaled_oancf
count  73695.00      73695.00
mean      -0.06          0.08
std        0.90          0.14
min     -150.12         -9.05
25%       -0.08          0.04
50%       -0.04          0.08
75%       -0.01          0.13
max      168.98          3.36

# Future Returns Analysis

Explore how firms perform over following year based on current cash flows and accruals ranking

In [24]:
# assign each observation into one of 5 groups based on accruals.
df['accruals_ranking'] = pd.qcut(df['accruals'], 5, labels=[1,2,3,4,5])

# do the same for cash flows
df['oancf_ranking'] = pd.qcut(df['scaled_oancf'], 5, labels=[1,2,3,4,5])

Examine future returns for firms with high vs low accruals

In [25]:
accruals_summary = df.pivot_table(index=['accruals_ranking'], values=['annret'], aggfunc='median')

accruals_summary

                    annret
accruals_ranking
1                 0.090090
2                 0.101067
3                 0.099334
4                 0.087940
5                 0.045262

Firms with high accruals (rank 5) perform worse than firms with low accruals (rank 1)

Examine future returns for high vs low cash flows

In [26]:
cash_flow_summary = df.pivot_table(index=['oancf_ranking'], values=['annret'], aggfunc='median')
cash_flow_summary

                 annret
oancf_ranking
1              0.005326
2              0.095825
3              0.103448
4              0.103309
5              0.106028

Combine both

In [31]:
summary = df.pivot_table(index=['accruals_ranking', 'oancf_ranking'], values=['annret'], aggfunc='median')
summary = summary.unstack('oancf_ranking')
summary

                    annret
oancf_ranking            1         2         3         4         5
accruals_ranking
1                -0.109375  0.115790  0.134437  0.111842  0.109759
2                -0.053305  0.097222  0.110788  0.106165  0.112446
3                -0.048632  0.101834  0.106402  0.105500  0.113908
4                 0.031239  0.103789  0.101514  0.097751  0.082689
5                 0.027315  0.064991  0.062628  0.072309  0.031209

# Results

The above analysis concludes that: <br/>
Firms with high cash flows and low accruals perform better than firms with high accruals and low cash flows